// prisma imports
import { PrismaClient } from "@prisma/client";
import { InstrumentCategory } from "./util";
const prisma = new PrismaClient();

// insert instrument types
// all 4
export const createInstrumentTypes = async () => {
  try {
    const allTypes = await prisma.instrumenttype.createMany({
      data: [
        { name: InstrumentCategory.Guitar, id: 1 },
        { name: InstrumentCategory.Acoustic, id: 2 },
        { name: InstrumentCategory.Bass, id: 3 },
        { name: InstrumentCategory.AmpsEffects, id: 4 },
      ],
    });
    console.log(allTypes);
  } finally {
    await prisma.$disconnect();
  }
};

// insert years
export const addYears = async () => {
  try {
    const allTypes = await prisma.years.createMany({
      data: [
        { year: 1876 },
        { year: 1877 },
        { year: 1878 },
        { year: 1879 },
        { year: 1880 },
        { year: 1881 },
        { year: 1882 },
        { year: 1883 },
        { year: 1884 },
        { year: 1885 },
        { year: 1886 },
        { year: 1887 },
        { year: 1888 },
        { year: 1889 },
        { year: 1890 },
        { year: 1891 },
        { year: 1892 },
        { year: 1893 },
        { year: 1894 },
        { year: 1895 },
        { year: 1896 },
        { year: 1897 },
        { year: 1898 },
        { year: 1899 },
        { year: 1900 },
        { year: 1901 },
        { year: 1902 },
        { year: 1903 },
        { year: 1904 },
        { year: 1905 },
        { year: 1906 },
        { year: 1907 },
        { year: 1908 },
        { year: 1909 },
        { year: 1910 },
        { year: 1911 },
        { year: 1912 },
        { year: 1913 },
        { year: 1914 },
        { year: 1915 },
        { year: 1916 },
        { year: 1917 },
        { year: 1918 },
        { year: 1919 },
        { year: 1920 },
        { year: 1921 },
        { year: 1922 },
        { year: 1923 },
        { year: 1924 },
        { year: 1925 },
        { year: 1926 },
        { year: 1927 },
        { year: 1928 },
        { year: 1929 },
        { year: 1930 },
        { year: 1931 },
        { year: 1932 },
        { year: 1933 },
        { year: 1934 },
        { year: 1935 },
        { year: 1936 },
        { year: 1937 },
        { year: 1938 },
        { year: 1939 },
        { year: 1940 },
        { year: 1941 },
        { year: 1942 },
        { year: 1943 },
        { year: 1944 },
        { year: 1945 },
        { year: 1946 },
        { year: 1947 },
        { year: 1948 },
        { year: 1949 },
        { year: 1950 },
        { year: 1951 },
        { year: 1952 },
        { year: 1953 },
        { year: 1954 },
        { year: 1955 },
        { year: 1956 },
        { year: 1957 },
        { year: 1958 },
        { year: 1959 },
        { year: 1960 },
        { year: 1961 },
        { year: 1962 },
        { year: 1963 },
        { year: 1964 },
        { year: 1965 },
        { year: 1966 },
        { year: 1967 },
        { year: 1968 },
        { year: 1969 },
        { year: 1970 },
        { year: 1971 },
        { year: 1972 },
        { year: 1973 },
        { year: 1974 },
        { year: 1975 },
        { year: 1976 },
        { year: 1977 },
        { year: 1978 },
        { year: 1979 },
        { year: 1980 },
        { year: 1981 },
        { year: 1982 },
        { year: 1983 },
        { year: 1984 },
        { year: 1985 },
        { year: 1986 },
        { year: 1987 },
        { year: 1988 },
        { year: 1989 },
        { year: 1990 },
        { year: 1991 },
        { year: 1992 },
        { year: 1993 },
        { year: 1994 },
        { year: 1995 },
        { year: 1996 },
        { year: 1997 },
        { year: 1998 },
        { year: 1999 },
        { year: 2000 },
        { year: 2001 },
        { year: 2002 },
        { year: 2003 },
        { year: 2004 },
        { year: 2005 },
        { year: 2006 },
        { year: 2007 },
        { year: 2008 },
        { year: 2009 },
        { year: 2010 },
        { year: 2011 },
        { year: 2012 },
        { year: 2013 },
        { year: 2014 },
        { year: 2015 },
        { year: 2016 },
        { year: 2017 },
        { year: 2018 },
        { year: 2019 },
        { year: 2020 },
        { year: 2021 },
        { year: 2022 },
        { year: 2023 },
      ],
    });
  } finally {
    await prisma.$disconnect();
  }
};

export const addBrands = async() => {
  // populated list of brands to use
  try {
    const allTypes = await prisma.brands.createMany({
      data: [
        {brand: "fender"},
        {brand: "gibson"},
        {brand: "ibanez"},
        {brand: "prs (paul reed smith)"},
        {brand: "jackson"},
        {brand: "esp"},
        {brand: "schecter"},
        {brand: "epiphone"},
        {brand: "yamaha"},
        {brand: "music man"},
        {brand: "taylor"},
        {brand: "martin"},
        {brand: "gretsch"},
        {brand: "rickenbacker"},
        {brand: "ernie ball"},
        {brand: "d'addario"},
        {brand: "fender custom shop"},
        {brand: "squier"},
        {brand: "hofner"},
        {brand: "cort"},
        {brand: "warwick"},
        {brand: "sterling by music man"},
        {brand: "danelectro"},
        {brand: "g&l"},
        {brand: "guild"},
        {brand: "c.f. martin & co."},
        {brand: "godin"},
        {brand: "seagull"},
        {brand: "suhr"},
        {brand: "knaggs"},
        {brand: "collings"},
        {brand: "b.c. rich"},
        {brand: "carvin"},
        {brand: "dean"},
        {brand: "lakland"},
        {brand: "spector"},
        {brand: "peavey"},
        {brand: "ampeg"},
        {brand: "marshall"},
        {brand: "vox"},
        {brand: "orange"},
        {brand: "mesa/boogie"},
        {brand: "blackstar"},
        {brand: "line 6"},
        {brand: "roland"},
        {brand: "boss"},
        {brand: "electro-harmonix"},
        {brand: "tc electronic"},
        {brand: "mxr"},
        {brand: "dunlop"},
        {brand: "pro co"},
        {brand: "fulltone"},
        {brand: "earthquaker devices"},
        {brand: "strymon"},
        {brand: "wampler"},
        {brand: "digitech"},
        {brand: "ehx (electro-harmonix)"},
        {brand: "walrus audio"},
        {brand: "jhs pedals"},
        {brand: "empress effects"},
        {brand: "tech 21"},
        {brand: "darkglass electronics"},
        {brand: "korg"},
        {brand: "zoom"},
        {brand: "behringer"},
        {brand: "mooer"},
        {brand: "walden"},
        {brand: "gallien-krueger"},
        {brand: "trace elliot"},
        {brand: "aguilar"},
        {brand: "hartke"},
        {brand: "markbass"},
        {brand: "ashdown"},
        {brand: "swr (swr sound corporation)"},
        {brand: "eden"},
        {brand: "genzler amplification"},
        {brand: "acoustic image"},
        {brand: "aer (audio electric research)"},
        {brand: "markbass (amps)"},
        {brand: "takamine"},
        {brand: "washburn"},
        {brand: "kramer"},
        {brand: "fernandes"},
        {brand: "suzuki"},
        {brand: "alvarez"},
        {brand: "ovation"},
        {brand: "guild (amps)"},
        {brand: "line 6 (amps)"},
        {brand: "fishman"},
        {brand: "hughes & kettner"},
        {brand: "randall"},
        {brand: "traynor"},
        {brand: "bugera"},
        {brand: "kustom"},
        {brand: "crate"},
        {brand: "peavey (bass amps)"},
        {brand: "genz benz"},
        {brand: "orange (amps)"},
        {brand: "evh (eddie van halen)"},
        {brand: "rocktron"},
        {brand: "voodoo lab"},
        {brand: "dunlop (cry baby)"},
        {brand: "ibanez (tubescreamer)"},
        {brand: "mooer (micro series)"},
        {brand: "jackson (amps)"},
        {brand: "evans"},
        {brand: "aquarian"},
        {brand: "remo"},
        {brand: "pdp (dw drums)"},
        {brand: "pearl"},
        {brand: "tama"},
        {brand: "ludwig"},
        {brand: "mapex"},
        {brand: "sonor"},
        {brand: "gibraltar"},
        {brand: "vic firth"},
        {brand: "zildjian"},
        {brand: "sabian"},
        {brand: "meinl"},
        {brand: "paiste"},
        {brand: "ufip"},
        {brand: "istanbul agop"},
        {brand: "dream cymbals"},
        {brand: "electro-voice"},
        {brand: "shure"},
        {brand: "sennheiser"},
        {brand: "akg"},
        {brand: "audio-technica"},
        {brand: "beyerdynamic"},
        {brand: "rode"},
        {brand: "blue microphones"},
        {brand: "neumann"},
        {brand: "zoom (audio recorders)"},
        {brand: "line 6 (recording)"},
        {brand: "focusrite"},
        {brand: "presonus"},
        {brand: "behringer (audio interfaces)"},
        {brand: "art (applied research & technology)"},
        {brand: "motu (mark of the unicorn)"},
        {brand: "tascam"},
        {brand: "m-audio"},
        {brand: "akai professional"},
        {brand: "native instruments"},
        {brand: "alesis"},
        {brand: "korg (synthesizers)"},
        {brand: "roland (synthesizers)"},
        {brand: "moog"},
        {brand: "dave smith instruments"},
        {brand: "novation"},
        {brand: "arturia"},
        {brand: "yamaha (synthesizers)"},
        {brand: "kurzweil"},
        {brand: "clavia"}
      ]
      
    });
    console.log('brands: ',allTypes);
  } finally {
    await prisma.$disconnect();
  }
}

export const initdb = async () => {
  // await createInstrumentTypes();
  // await addYears();
  await addBrands();
};