import { z } from "zod";

export const NFTBassObject = z.object({
    bodyMaterial: z.string(),
    brand: z.string(),
    case: z.string(),
    electronics: z.string(),
    finish: z.string(),
    finishMaterial: z.string(),
    handedness: z.string(),
    // image: z.string().transform((val) => Buffer.from(val.replace(/^data:image\/\w+;base64,/, ""), 'base64')),
    model: z.string(),
    mods: z.string(),
    neckFingerboard: z.string(),
    neckProfile: z.string(),
    neckThickness: z.string(),
    nutWidth: z.string(),
    pickupImpedance: z.string(),
    potCodes: z.string(),
    radius: z.string(),
    scaleLength: z.string(),
    serial: z.string(),
    tuners: z.string(),
    weight: z.string(),
    year: z.number(),
}).required();

export const NFTGuitarObject = z.object({
    bodyMaterial: z.string(),
    brand: z.string(),
    case: z.string(),
    containsBrazilianRosewood: z.string(),
    electronics: z.string(),
    finish: z.string(),
    finishMaterial: z.string(),
    handedness: z.string(),
    // image: z.string().transform((val) => Buffer.from(val.replace(/^data:image\/\w+;base64,/, ""), 'base64')),
    instrumentType: z.string(),
    madeInYear: z.string(),
    model: z.string(),
    modificationsRepairs: z.string(),
    neckFingerboard: z.string(),
    neckProfile: z.string(),
    neckThickness: z.string(),
    nutWidth: z.string(),
    pickupImpedance: z.string(),
    potCodes: z.string(),
    radius: z.string(),
    scaleLength: z.string(),
    tuners: z.string(),
    weight: z.string(),
}).required();

export const NFTAcousticObject = z.object({

    backAndSides: z.string(),
    // image: z.string().transform((val) => Buffer.from(val.replace(/^data:image\/\w+;base64,/, ""), 'base64')),
    bracePattern: z.string(),
    brand: z.string(),
    bridge: z.string(),
    case: z.string(),
    containsBrazilianRosewood: z.string(),
    electronics: z.string(),
    fingerboardRadius: z.string(),
    finish: z.string(),
    finishMaterial: z.string(),
    handedness: z.string(),
    madeInYear: z.string(),
    model: z.string(),
    modificationsRepairs: z.string(),
    neckDepth: z.string(),
    neckFingerboard: z.string(),
    neckProfile: z.string(),
    nutWidth: z.string(),
    scaleLength: z.string(),
    serialNumber: z.string(),
    stringSpacingAtSaddle: z.string(),
    top: z.string(),
    tuners: z.string(),
}).required();

export const NFTAmpFxObject = z.object({

    // image: z.string().transform((val) => Buffer.from(val.replace(/^data:image\/\w+;base64,/, ""), 'base64')),
    brand: z.string(),
    choke: z.string(),
    circuit: z.string(),
    finish: z.string(),
    instrument: z.string(),
    madeInYear: z.string(),
    model: z.string(),
    power: z.string(),
    preamp: z.string(),
    rectifier: z.string(),
    reverbOther: z.string(),
    serialNumber: z.string(),
    speaker: z.string(),
    speakerCodes: z.string(),
    transformersOT: z.string(),
    transformersPT: z.string(),
    wattage: z.string()

}).required();
